version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dependabot-updates
  ignore:
  - dependency-name: emotion
    versions:
    - "> 10.0.9, < 11"
  - dependency-name: gatsby-image
    versions:
    - "> 2.2.7, < 3"
  - dependency-name: gatsby-plugin-feed
    versions:
    - "> 2.2.3, < 3"
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - "> 2.1.4, < 3"
  - dependency-name: gatsby-plugin-manifest
    versions:
    - "> 2.2.4, < 3"
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - "> 3.0.12, < 4"
  - dependency-name: gatsby-plugin-sass
    versions:
    - "> 2.1.3, < 3"
  - dependency-name: gatsby-plugin-sharp
    versions:
    - "> 2.2.9, < 3"
  - dependency-name: gatsby-remark-images
    versions:
    - "> 3.1.7, < 4"
  - dependency-name: gatsby-source-filesystem
    versions:
    - "> 2.1.6, < 3"
  - dependency-name: gatsby-transformer-remark
    versions:
    - "> 2.6.5, < 3"
  - dependency-name: react
    versions:
    - "> 16.8.6, < 17"
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.11
    - 2.32.3
    - 2.32.4
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: gatsby-plugin-catch-links
    versions:
    - 2.9.0
